FROM node:alpine 

RUN apk update && apk upgrade && \
  apk add --no-cache bash coreutils

WORKDIR /usr/src/app 

COPY package.json ./ 

RUN npm install

COPY . ./ 

RUN chmod +x scripts/wait-for-it.sh

CMD ["npm", "run", "start:dev"]
